### ISSUE TITLE
Typos in script files that have not yet been fixed

### ISSUE THREAD

**Issue by Herbie60D** [storm-devs/coas#2]
Hello @Hammie 
I found some typos in the files postet in CoAS-Remastered-1.0.1.zip. (https://www.piratesahoy.net/threads/city-of-abandoned-ships-remastered-alpha-release.33328/) and since they are not yet fixed here so far, I thought I'll post what I found. The first one is not in the original game files, but the others are. I hope the information is helpful. Keep up the good work.

Program\Controls\init_pc.c
- line 33 - The first character should be a space, but is a '†'. It's not in the original game files, so...

Program\Weather\init\Morning.c
- line 535 - A semicolon is missing before the comment starts.

Program\DIALOGS\russian\Quest\ForAll_dialog.c
- line 2549 - A semicolon is missing before the comment starts.

Program\DIALOGS\russian\Quest\PiratesLine_dialog.c
- line 643 - This line should be a comment, right?

Program\DIALOGS\russian\Quest\LostShipsCity\Priest.c
- line 48 - This line should be a comment, right?

Program\DIALOGS\russian\Shipyard\Pirates_Shipyard.c
- lines 22 to 24 - The three variables all start with the Russian letter 'с' instead of the Latin letter 'c'. This is probably no Problem but the code parts should use ASCII character set.

RESOURCE\animation
armor.ani (line 1142), man.ani (line 1148), swim.ani (line 1156)
- A semicolon is missing. These lines should be a comments, right?

**Comment by Hammie** [comment]
Thank you for the fixes! I applied them to the repository.

I don't have the time to actively maintain this project, but any fixes like this are always welcome :+1:
